# How to merge multiple CSV files with Python
Python convert normal JSON to JSON separated lines 3 examples

* Steps to merge multiple CSV(identical) files with Python
* Steps to merge multiple CSV(identical) files with Python with trace
* Combine multiple CSV files when the columns are different
* Bonus: Merge multiple files with Windows/Linux

## 1. Steps to merge multiple CSV(identical) files with Python

In [1]:
import os, glob
import pandas as pd

path = "../../csv/"

all_files = glob.glob(os.path.join(path, "data_2019*.csv"))

all_csv = (pd.read_csv(f, sep=',') for f in all_files)
df_merged   = pd.concat(all_csv, ignore_index=True)
df_merged.to_csv( "merged.csv")

## 2. Steps to merge multiple CSV(identical) files with Python with trace

In [2]:
import os, glob
import pandas as pd

path = "../../csv/"

all_files = glob.glob(os.path.join(path, "data_2019*.csv"))

all_df = []
for f in all_files:
    df = pd.read_csv(f, sep=',')
    df['file'] = f.split('/')[-1]
    all_df.append(df)
    
merged_df = pd.concat(all_df, ignore_index=True)
merged_df

  col1 col2  col3             file
0    C    D     3  data_201902.csv
1   CC   DD     4  data_201902.csv
2    A    B     1  data_201901.csv
3   AA   BB     2  data_201901.csv

## 3. Combine multiple CSV files when the columns are different

In [7]:
import os, glob
import pandas as pd

path = "../../csv/"

all_files = glob.glob(os.path.join(path, "data_*.csv"))


all_df = []
for f in all_files:
    df = pd.read_csv(f, sep=',')
    df['file'] = f.split('/')[-1]
    all_df.append(df)
    
merged_df = pd.concat(all_df, ignore_index=True, sort=True)
merged_df

  col1 col2  col3 col4  col5             file
0    E    F     5   e5   NaN  data_202001.csv
1   EE   FF     6  ee6   NaN  data_202001.csv
2    H    J     7  NaN  77.0  data_202002.csv
3   HH   JJ     8  NaN  88.0  data_202002.csv
4    C    D     3  NaN   NaN  data_201902.csv
5   CC   DD     4  NaN   NaN  data_201902.csv
6    A    B     1  NaN   NaN  data_201901.csv
7   AA   BB     2  NaN   NaN  data_201901.csv

## 4. Bonus: Merge multiple files with Windows/Linux

Linux

`sed 1d data_*.csv > merged.csv`

Windows

`C:\> copy data_*.csv merged.csv `