# 21. Pandas - Random Sample of a subset of a dataframe

In [1]:
import pandas as pd
df = pd.read_csv("../csv/movie_metadata.csv")

## 1. Random sampling of rows, columns from DataFrame with sample()

In [2]:
# Default behavior of sample()
df.sample()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
2525,Color,Joel Schumacher,106.0,98.0,541.0,71.0,David Murray,214.0,1569918.0,Biography|Crime|Drama|Thriller,...,113.0,English,Ireland,R,17000000.0,2003.0,96.0,6.9,2.35,0

In [3]:
# return n rows
df.sample(3)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
535,Color,Dennis Dugan,179.0,102.0,221.0,4000.0,Adam Sandler,12000.0,162001186.0,Comedy,...,311.0,English,USA,PG-13,80000000.0,2010.0,11000.0,6.0,1.85,12000
2987,Color,Fred Schepisi,61.0,109.0,40.0,794.0,Ray Winstone,5000.0,2326407.0,Drama,...,99.0,English,UK,R,12000000.0,2001.0,1000.0,7.0,2.35,305
1475,Color,David Koepp,248.0,91.0,192.0,346.0,Dania Ramirez,23000.0,20275446.0,Action|Crime|Thriller,...,178.0,English,USA,PG-13,35000000.0,2012.0,1000.0,6.5,2.35,20000

In [4]:
# columns
df.sample(3, axis=1).head()

   color  num_critic_for_reviews  title_year
0  Color                   723.0      2009.0
1  Color                   302.0      2007.0
2  Color                   602.0      2015.0
3  Color                   813.0      2012.0
4    NaN                     NaN         NaN

In [5]:
# The fraction of rows and columns: frac
df.sample(frac=0.001)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
2389,Color,Terry Gilliam,156.0,118.0,0.0,551.0,Michael Jeter,40000.0,10562387.0,Adventure|Comedy|Drama,...,648.0,English,USA,R,18500000.0,1998.0,693.0,7.7,2.35,15000
4233,Black and White,Tay Garnett,7.0,119.0,10.0,275.0,Greer Garson,509.0,NaN,Drama,...,29.0,English,USA,Passed,2160000.0,1945.0,284.0,7.5,1.37,68
4737,Color,Greg Harrison,46.0,86.0,7.0,17.0,Ari Gold,328.0,1114943.0,Drama|Music,...,74.0,English,USA,R,500000.0,2000.0,27.0,6.5,1.85,0
3717,Color,Mike Flanagan,336.0,104.0,59.0,202.0,Rory Cochrane,972.0,27689474.0,Horror|Mystery,...,339.0,English,USA,R,5000000.0,2013.0,407.0,6.5,2.35,23000
1854,Color,Garry Marshall,200.0,113.0,0.0,307.0,Common,22000.0,54540525.0,Comedy|Romance,...,134.0,English,USA,PG-13,56000000.0,2011.0,988.0,5.7,1.85,20000

In [6]:
# sample with seed
df.sample(n=3, random_state=5)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
4232,Color,Hayley Cloake,11.0,90.0,0.0,306.0,Kayla Ewell,676.0,NaN,Thriller,...,9.0,English,USA,R,2200000.0,2008.0,399.0,4.3,NaN,77
4877,Color,Tom Seidman,4.0,98.0,3.0,104.0,Derek Brandon,337.0,NaN,Drama|Family,...,10.0,English,USA,PG,250000.0,2010.0,168.0,6.2,NaN,0
3399,Color,Mike Leigh,248.0,129.0,608.0,386.0,Imelda Staunton,1000.0,3205244.0,Comedy|Drama,...,141.0,English,UK,PG-13,10000000.0,2010.0,579.0,7.3,2.35,0

## 2. p.random.choice

In [7]:
# nu,py choice for DataFrame sampling
import numpy as np
chosen_idx = np.random.choice(1000, replace=False, size=5)
df.iloc[chosen_idx]

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
893,Color,Gabriele Muccino,202.0,123.0,125.0,835.0,Rosario Dawson,10000.0,69951824.0,Drama|Romance,...,599.0,English,USA,PG-13,55000000.0,2008.0,3000.0,7.7,2.35,26000
818,Color,Brian Levant,57.0,90.0,32.0,809.0,Mark Addy,1000.0,35231365.0,Comedy|Family|Romance|Sci-Fi,...,85.0,English,USA,PG,60000000.0,2000.0,891.0,3.6,1.85,500
460,Color,Simon West,139.0,123.0,165.0,744.0,Monica Potter,12000.0,101087161.0,Action|Crime|Thriller,...,339.0,English,USA,R,75000000.0,1997.0,878.0,6.8,2.35,0
772,Color,Clint Eastwood,306.0,134.0,16000.0,204.0,Morgan Freeman,13000.0,37479778.0,Biography|Drama|History|Sport,...,259.0,English,USA,PG-13,60000000.0,2009.0,11000.0,7.4,2.35,23000
269,Color,Len Wiseman,354.0,129.0,235.0,297.0,Jonathan Sadowski,13000.0,134520804.0,Action|Adventure|Thriller,...,782.0,English,USA,PG-13,110000000.0,2007.0,300.0,7.2,2.35,0

## 3. Random sample of rows based on column values

In [8]:
# conditional DataFrame sampling few values - separate display 
col = 'color'
for typ in list(df[col].dropna().unique()):
    print(typ, end=' - ')
    display(df[df[col] == typ].sample(3))

Color -

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
2693,Color,Albert Brooks,97.0,97.0,745.0,745.0,Bradley Whitford,12000.0,11614236.0,Comedy,...,140.0,English,USA,PG-13,15000000.0,1999.0,821.0,5.6,1.37,251
1613,Color,Alexander Payne,217.0,125.0,729.0,322.0,June Squibb,442.0,65010106.0,Comedy|Drama,...,612.0,English,USA,R,30000000.0,2002.0,344.0,7.2,1.85,0
698,Color,Lawrence Kasdan,40.0,212.0,759.0,812.0,Catherine O'Hara,2000.0,25052000.0,Adventure|Biography|Crime|Drama|Western,...,145.0,English,USA,PG-13,63000000.0,1994.0,925.0,6.6,2.35,0

 Black and White -

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
4786,Black and White,Lloyd Bacon,65.0,89.0,24.0,45.0,Dick Powell,610.0,2300000.0,Comedy|Musical|Romance,...,97.0,English,USA,Unrated,439000.0,1933.0,105.0,7.7,1.37,439
3983,Black and White,John Schlesinger,88.0,113.0,154.0,77.0,Barnard Hughes,183.0,NaN,Drama,...,334.0,English,USA,X,3600000.0,1969.0,89.0,7.9,1.85,0
479,Black and White,NaN,31.0,25.0,NaN,474.0,Agnes Moorehead,1000.0,NaN,Comedy|Family|Fantasy,...,71.0,English,USA,TV-G,NaN,NaN,960.0,7.6,4.00,0

In [9]:
# conditional DataFrame sampling many values - grouped display 
col = 'content_rating'
sample = []

variants = list(df[col].dropna().unique())
print(variants)

for typ in variants:
    sample.append(df[df[col] == typ].sample())
pd.concat(sample)

['PG-13', 'PG', 'G', 'R', 'TV-14', 'TV-PG', 'TV-MA', 'TV-G', 'Not Rated', 'Unrated', 'Approved', 'TV-Y', 'NC-17', 'X', 'TV-Y7', 'GP', 'Passed', 'M']

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
3758,Color,Brian Dannelly,121.0,92.0,12.0,797.0,Patrick Fugit,3000.0,8786715.0,Comedy|Drama,...,324.0,English,USA,PG-13,5000000.0,2004.0,835.0,6.9,1.85,0
64,Color,Andrew Adamson,284.0,150.0,80.0,82.0,Kiran Shah,1000.0,291709845.0,Adventure|Family|Fantasy,...,1463.0,English,USA,PG,180000000.0,2005.0,190.0,6.9,2.35,0
4725,Color,Joe Camp,5.0,86.0,24.0,142.0,Peter Breck,407.0,39552600.0,Adventure|Family|Romance,...,36.0,English,USA,G,500000.0,1974.0,189.0,6.1,1.85,816
2955,Color,Franklin J. Schaffner,55.0,125.0,76.0,801.0,Anne Meara,1000.0,NaN,Drama|Thriller,...,123.0,English,UK,R,12000000.0,1978.0,837.0,7.0,1.85,0
3509,Color,NaN,11.0,60.0,NaN,652.0,Ashley Scott,10000.0,NaN,Action|Drama|Mystery|Sci-Fi,...,160.0,English,USA,TV-14,NaN,NaN,794.0,7.4,1.33,0
4803,Color,NaN,11.0,22.0,NaN,6.0,Ron Lynch,59.0,NaN,Animation|Comedy|Drama,...,82.0,English,USA,TV-PG,NaN,NaN,11.0,8.2,1.33,526
826,Color,NaN,46.0,30.0,NaN,479.0,Kristin Davis,962.0,NaN,Comedy|Romance,...,238.0,English,USA,TV-MA,NaN,NaN,722.0,7.0,1.33,0
3880,Color,Kenny Ortega,57.0,98.0,197.0,578.0,Corbin Bleu,755.0,NaN,Comedy|Drama|Family|Music|Musical|Romance,...,726.0,English,USA,TV-G,4200000.0,2006.0,632.0,5.2,1.33,0
4328,Black and White,Orson Welles,90.0,92.0,0.0,18.0,Everett Sloane,1000.0,7927.0,Crime|Drama|Film-Noir|Mystery|Thriller,...,175.0,English,USA,Not Rated,2300000.0,1947.0,29.0,7.7,1.37,0
4997,Color,David Gordon Green,75.0,90.0,234.0,15.0,Eddie Rouse,552.0,241816.0,Drama,...,76.0,English,USA,Unrated,42000.0,2000.0,61.0,7.5,2.35,451
4497,Black and White,Walter Lang,7.0,83.0,9.0,51.0,Nigel Bruce,94.0,NaN,Drama|Family|Fantasy,...,25.0,English,USA,Approved,NaN,1940.0,62.0,6.5,1.37,548
1265,Color,NaN,3.0,30.0,NaN,12.0,Melissa Altro,51.0,NaN,Animation|Comedy|Family,...,43.0,English,Canada,TV-Y,NaN,NaN,21.0,7.4,1.33,301
5025,Color,John Waters,73.0,108.0,0.0,105.0,Mink Stole,462.0,180483.0,Comedy|Crime|Horror,...,183.0,English,USA,NC-17,10000.0,1972.0,143.0,6.1,1.37,0
3559,Color,Brian De Palma,121.0,104.0,0.0,517.0,David Margulies,754.0,31899000.0,Mystery|Romance|Thriller,...,201.0,English,USA,X,6500000.0,1980.0,567.0,7.1,2.35,0
1972,Color,NaN,7.0,30.0,NaN,265.0,Jennifer Hale,971.0,NaN,Action|Animation|Comedy|Family|Fantasy|Sci-Fi,...,60.0,English,USA,TV-Y7,NaN,NaN,918.0,7.2,4.00,581
4529,Color,Douglas Trumbull,87.0,89.0,136.0,42.0,Ron Rifkin,844.0,NaN,Drama|Sci-Fi,...,199.0,English,USA,GP,1000000.0,1972.0,184.0,6.7,1.85,0
4812,Black and White,Harry Beaumont,36.0,100.0,4.0,4.0,Bessie Love,77.0,2808000.0,Musical|Romance,...,71.0,English,USA,Passed,379000.0,1929.0,28.0,6.3,1.37,167
3584,Color,George Roy Hill,130.0,110.0,131.0,399.0,Ted Cassidy,640.0,102308900.0,Biography|Crime|Drama|Western,...,309.0,English,USA,M,6000000.0,1969.0,566.0,8.1,2.35,0

## 4. Dataframe sampling with numpy and weights

In [15]:
# excluding 'Color' values by applying weights 0 - Color and 1 - rest
df['weights'] = np.where(df['color'] == 'Color', .0, 1)
df.sample(frac=.001, weights='weights')

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,weights
2425,Black and White,Martin Scorsese,151.0,121.0,17000.0,356.0,Cathy Moriarty,22000.0,45250.0,Biography|Drama|Sport,...,English,USA,R,18000000.0,1980.0,394.0,8.3,1.85,0,1.0
1125,Black and White,Oliver Stone,83.0,212.0,0.0,805.0,Bob Hoskins,12000.0,13560960.0,Biography|Drama|History,...,English,USA,R,50000000.0,1995.0,5000.0,7.1,2.35,915,1.0
3539,NaN,Richard Rich,2.0,45.0,24.0,29.0,Kate Higgins,122.0,NaN,Action|Adventure|Animation|Comedy|Drama|Family...,...,NaN,USA,NaN,7000000.0,2014.0,35.0,6.0,NaN,41,1.0
2944,Black and White,Martin Campbell,400.0,144.0,258.0,834.0,Tobias Menzies,6000.0,167007184.0,Action|Adventure|Thriller,...,English,UK,PG-13,150000000.0,2006.0,1000.0,8.0,2.35,0,1.0
4359,Black and White,Stanley Kubrick,192.0,95.0,0.0,277.0,Slim Pickens,654.0,NaN,Comedy,...,English,USA,PG,1800000.0,1964.0,575.0,8.5,1.66,18000,1.0

In [16]:
# Including only 'Color' values by applying weights 1 - Color and 0 - rest
df['weights'] = np.where(df['color'] == 'Color', 1, 0.0)
df.sample(frac=.001, weights='weights')

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,weights
3083,Color,Floyd Mutrux,5.0,99.0,11.0,327.0,Kelli Williams,665.0,125169.0,Comedy|Drama,...,English,USA,R,10500000.0,1994.0,446.0,6.4,NaN,119,1.0
3435,Color,George Tillman Jr.,34.0,115.0,88.0,890.0,Mekhi Phifer,1000.0,43490057.0,Comedy|Drama,...,English,USA,R,7500000.0,1997.0,1000.0,6.9,1.85,508,1.0
3940,Color,Renny Harlin,68.0,102.0,212.0,195.0,Lane Smith,10000.0,354704.0,Crime|Drama|Horror|Thriller,...,English,USA,R,1300000.0,1987.0,633.0,5.9,1.85,314,1.0
5006,Color,Damir Catic,NaN,89.0,2.0,0.0,Ron Gelner,5.0,NaN,Horror,...,English,USA,Not Rated,60000.0,2013.0,0.0,5.4,NaN,48,1.0
1872,Color,Michael Hoffman,85.0,118.0,97.0,437.0,Gerald McRaney,775.0,26761283.0,Drama|Romance,...,English,USA,PG-13,26000000.0,2014.0,523.0,6.7,2.35,19000,1.0

In [17]:
np.where(df['color'] == 'Color', 1, 0)[270:280]

array([1, 1, 0, 1, 1, 1, 1, 1, 1, 0])

In [18]:
print(list(df['color'][270:280]))

['Color', 'Color', ' Black and White', 'Color', 'Color', 'Color', 'Color', 'Color', 'Color', nan]

In [19]:
# Including/excluding list of values - with equal probability
df['weights'] = np.where(df['content_rating'].isin(['PG-13', 'PG', 'G']), 1, 0)
df.sample(frac=.002, weights='weights')['content_rating']

2153       PG
2238    PG-13
836     PG-13
4725        G
3205       PG
3388    PG-13
152     PG-13
2574    PG-13
2724    PG-13
1854    PG-13
Name: content_rating, dtype: object

In [20]:
df[df['content_rating'].isin(['PG-13', 'PG', 'G'])]['content_rating'].value_counts()

PG-13    1461
PG        701
G         112
Name: content_rating, dtype: int64

## 5. Pandas sample rows by group

In [22]:
df.groupby('color').apply(lambda x: x.sample(n=3))

                                  color      director_name  \
color
 Black and White 2734   Black and White         Fritz Lang
                 4741   Black and White  Morgan J. Freeman
                 1979   Black and White        Neil Jordan
Color            3436             Color       Stanley Tong
                 734              Color       Oliver Stone
                 2336             Color     Andrew Jarecki

                       num_critic_for_reviews  duration  \
color
 Black and White 2734                   260.0     145.0
                 4741                    17.0      86.0
                 1979                    44.0     133.0
Color            3436                    62.0      89.0
                 734                    171.0     156.0
                 2336                   140.0     101.0

                       director_facebook_likes  actor_3_facebook_likes  \
color
 Black and White 2734                    756.0                    18.0
                 4741                    204.0                   474.0
                 1979                    277.0                  8000.0
Color            3436                      7.0                    36.0
                 734                       0.0                  1000.0
                 2336                     46.0                   902.0

                            actor_2_name  actor_1_facebook_likes       gross  \
color
 Black and White 2734    Gustav Fröhlich                   136.0     26435.0
                 4741  Heather Matarazzo                   659.0    334041.0
                 1979        Liam Neeson                 25000.0  11030963.0
Color            3436          Anita Mui                   186.0  32333860.0
                 734        Dennis Quaid                 14000.0  75530832.0
                 2336      Kirsten Dunst                 33000.0    578382.0

                                                     genres  ...   language  \
color                                                        ...
 Black and White 2734                          Drama|Sci-Fi  ...     German
                 4741                   Crime|Drama|Romance  ...    English
                 1979          Biography|Drama|Thriller|War  ...    English
Color            3436                         Action|Comedy  ...  Cantonese
                 734                            Drama|Sport  ...    English
                 2336  Crime|Drama|Mystery|Romance|Thriller  ...    English

                         country  content_rating      budget title_year  \
color
 Black and White 2734    Germany       Not Rated   6000000.0     1927.0
                 4741        USA               R    500000.0     1997.0
                 1979         UK               R  28000000.0     1996.0
Color            3436  Hong Kong               R   7500000.0     1995.0
                 734         USA               R  55000000.0     1999.0
                 2336        USA               R         NaN     2010.0

                       actor_2_facebook_likes imdb_score aspect_ratio  \
color
 Black and White 2734                    23.0        8.3         1.33
                 4741                   529.0        6.5         1.85
                 1979                 14000.0        7.1         1.85
Color            3436                   147.0        6.7         2.35
                 734                   2000.0        6.8         2.35
                 2336                  4000.0        6.3         1.85

                       movie_facebook_likes weights
color
 Black and White 2734                 12000       0
                 4741                    51       0
                 1979                     0       0
Color            3436                     0       0
                 734                      0       0
                 2336                     0       0

[6 rows x 29 columns]

In [23]:
df.groupby('color').apply(lambda x: x.sample(n=3)).reset_index(drop = True)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,weights
0,Black and White,Steven Zaillian,127.0,128.0,234.0,581.0,Anthony Hopkins,14000.0,7221458.0,Drama|Thriller,...,English,Germany,PG-13,55000000.0,2006.0,12000.0,6.2,1.85,0,1
1,Black and White,Randy Moore,143.0,90.0,13.0,432.0,Lee Armstrong,977.0,169719.0,Fantasy|Horror,...,English,USA,Not Rated,NaN,2013.0,511.0,5.2,1.85,0,0
2,Black and White,Todd Haynes,231.0,135.0,162.0,228.0,Heath Ledger,23000.0,4001121.0,Biography|Drama|Music,...,English,USA,R,20000000.0,2007.0,13000.0,7.0,2.35,0,0
3,Color,Martin Brest,94.0,105.0,102.0,383.0,Ronny Cox,901.0,234760500.0,Action|Comedy|Crime,...,English,USA,R,14000000.0,1984.0,605.0,7.3,1.85,0,0
4,Color,Dario Argento,76.0,120.0,930.0,433.0,Adrienne Barbeau,982.0,349618.0,Horror,...,English,Italy,R,9000000.0,1990.0,602.0,6.1,1.85,375,0
5,Color,Tyler Perry,36.0,113.0,0.0,256.0,Mary J. Blige,607.0,51697449.0,Comedy|Drama,...,English,USA,PG-13,13000000.0,2009.0,269.0,4.1,1.85,1000,1

# Bonus: get first and last rows of DataFrame

In [24]:
df.head(2)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,weights
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000,1
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0,1

In [25]:
df.tail(2)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,weights
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660,1
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456,1

In [26]:
# combine head and tail variant 1
rows = 2
df.head(rows).append(df.tail(rows))

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,weights
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000,1
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0,1
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660,1
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456,1